nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': # Apply CORS to all paths starting with /api/
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            # allow_origin: ['https://your-frontend-app.com', 'http://localhost:3000']
            allow_headers: ['*'] # Often needed for API access
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']
            max_age: 3600
            # skip_ui_routes: false
            # origin_regex: true